x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: airflow.Dockerfile
  restart: always
  env_file: .env
  environment:
    AIRFLOW__CORE__EXECUTOR: ${AIRFLOW_EXECUTOR}
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@airflow-db:5432/${AIRFLOW_DB_NAME}
    AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW_FERNET_KEY}
    AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW_SECRET_KEY}
    AIRFLOW_CONN_POSTGRES_DEFAULT: ${AIRFLOW_CONN_POSTGRES_DEFAULT}
    AIRFLOW_CONN_CLICKHOUSE_DEFAULT: ${AIRFLOW_CONN_CLICKHOUSE_DEFAULT}
  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./scraper/books.csv:/opt/airflow/data/books.csv
  networks:
    - airflow_network

services:

  #Backend
  backend:
    env_file: .env
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "${BACKEND_PORT}:8000"
    environment:
      SEARCH_LEVENSHTEIN_DIR: /app/search_bundle
      UVICORN_RELOAD: ${UVICORN_RELOAD:-0}
    volumes:
      - ./src:/app/src
    depends_on:
      postgres:
        condition: service_healthy
      clickhouse:
        condition: service_started
    networks:
      - backend_network

  # React frontend served via Nginx
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - backend_network

  # Unit tests tester
  tester:
    env_file: .env
    build: 
      context: .
      dockerfile: tests.Dockerfile
    depends_on:
      - airflow-scheduler
      - backend
      - postgres
    networks:
      - backend_network
      - airflow_network

  # Airflow's dedicated database
  airflow-db:
    container_name: airflow-db
    image: postgres:13
    env_file: .env
    environment:
      POSTGRES_USER: ${AIRFLOW_DB_USER}
      POSTGRES_PASSWORD: ${AIRFLOW_DB_PASSWORD}
      POSTGRES_DB: ${AIRFLOW_DB_NAME}
    ports:
      - "${AIRFLOW_DB_PORT}:5432"
    volumes:
      - airflow_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${AIRFLOW_DB_USER} -d ${AIRFLOW_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - airflow_network

  # Backend database
  postgres:
    image: postgres:13
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - backend_network
      - airflow_network

  clickhouse:
    image: clickhouse:latest
    env_file: .env
    environment:
      CLICKHOUSE_DB: ${CLICKHOUSE_DB}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    ports:
      - "${CLICKHOUSE_PORT}:8123"
      - "${CLICKHOUSE_NATIVE_PORT}:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./init-clickhouse.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend_network
      - airflow_network
    restart: unless-stopped

  airflow-webserver:
    <<: *airflow-common
    depends_on:
      airflow-db:
        condition: service_healthy
    ports:
      - "8080:8080"
    command: >
      bash -c "
      while ! pg_isready -h airflow-db -p 5432 -U ${AIRFLOW_DB_USER}; do sleep 1; done &&
      airflow db init &&
      (airflow users create -u ${AIRFLOW_ADMIN_USERNAME} -p ${AIRFLOW_ADMIN_PASSWORD} -f ${AIRFLOW_ADMIN_FIRSTNAME} -l ${AIRFLOW_ADMIN_LASTNAME} -r Admin -e ${AIRFLOW_ADMIN_EMAIL}) &&
      airflow webserver
      "
    healthcheck:
      test: ["CMD-SHELL", "[ -f /opt/airflow/airflow-webserver.pid ]"]
      interval: 10s
      timeout: 10s
      retries: 10

  airflow-scheduler:
    <<: *airflow-common
    depends_on:
      airflow-db:
        condition: service_healthy
      airflow-webserver:
        condition: service_healthy
    command: >
      bash -c "
      while ! pg_isready -h airflow-db -p 5432 -U ${AIRFLOW_DB_USER}; do sleep 1; done &&
      airflow scheduler
      "

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    expose:
      - "9090"
    volumes:
      - ./config/prometheus:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - backend_network
      - airflow_network
    restart: unless-stopped

  postgres-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    container_name: postgres-exporter
    environment:
      DATA_SOURCE_NAME: ${POSTGRES_EXPORTER_DSN}
    depends_on:
      - postgres
    networks:
      - backend_network
    restart: unless-stopped

  airflow-db-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    container_name: airflow-db-exporter
    environment:
      DATA_SOURCE_NAME: ${AIRFLOW_DB_EXPORTER_DSN}
    depends_on:
      - airflow-db
    networks:
      - airflow_network
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "${GRAFANA_PORT}:3000"
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - backend_network
      - airflow_network
    restart: unless-stopped

volumes:
  airflow_db_data:
  postgres_data:
  clickhouse_data:
  prometheus_data:
  grafana_data:

networks:
  backend_network:
    driver: bridge
  airflow_network:
    driver: bridge