apiVersion: v1
kind: Service
metadata:
  name: airflow-db
  namespace: team-4-ns
spec:
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
  selector:
    app: airflow-db
  clusterIP: None
