apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
  namespace: team-4-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-scheduler
  template:
    metadata:
      labels:
        app: airflow-scheduler
    spec:
      containers:
        - name: scheduler
          image: woolfer0097kek/bookrec-airflow-scheduler:latest
          command: ["airflow", "scheduler"]
          env:
            - name: AIRFLOW__CORE__EXECUTOR
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: AIRFLOW_EXECUTOR
            - name: AIRFLOW__CORE__FERNET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: AIRFLOW_FERNET_KEY
            - name: AIRFLOW__WEBSERVER__SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: AIRFLOW_SECRET_KEY
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: AIRFLOW__CORE__SQL_ALCHEMY_CONN
          envFrom:
            - secretRef:
                name: app-secrets
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - airflow jobs check --job-type SchedulerJob --hostname "$(hostname)"
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 30
