apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-web
  namespace: book-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-web
  template:
    metadata:
      labels:
        app: airflow-web
    spec:
      containers:
        - name: web
          image: YOUR_DOCKERHUB/airflow:latest
          command: ["airflow", "webserver"]
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: app-secrets