apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: book-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: YOUR_DOCKERHUB/backend:latest
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: app-secrets
            - configMapRef:
                name: app-config