apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: clickhouse
  namespace: book-project
spec:
  serviceName: clickhouse
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      containers:
        - name: clickhouse
          image: clickhouse:latest
          ports:
            - containerPort: 9000
          envFrom:
            - secretRef:
                name: app-secrets
          volumeMounts:
            - name: data
              mountPath: /var/lib/clickhouse
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi