apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: team-4-ns
data:
  AIRFLOW_EXECUTOR: LocalExecutor

  POSTGRES_DB: backend
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"

  AIRFLOW_DB_NAME: airflow
  AIRFLOW_DB_HOST: airflow-db
  AIRFLOW_DB_PORT: "5432"

  CLICKHOUSE_DB: default
  CLICKHOUSE_HOST: clickhouse
  CLICKHOUSE_PORT: "8123"
  CLICKHOUSE_NATIVE_PORT: "9000"

  BACKEND_PORT: "8000"

  JWT_ACCESS_EXPIRE_MINUTES: "30"
  JWT_REFRESH_EXPIRE_DAYS: "14"
