apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: book-project
data:
  AIRFLOW_EXECUTOR: LocalExecutor

  POSTGRES_DB: backend
  AIRFLOW_DB_NAME: airflow
  CLICKHOUSE_DB: default

  BACKEND_PORT: "8000"

  JWT_ACCESS_EXPIRE_MINUTES: "30"
  JWT_REFRESH_EXPIRE_DAYS: "14"