apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
  namespace: team-4-ns
spec:
  accessModes: ["ReadWriteOnce"]
  volumeName: grafana-pv-new
  resources:
    requests:
      storage: 2Gi
