apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: team-4-ns
type: Opaque
stringData:

  AIRFLOW_EXECUTOR: LocalExecutor
  AIRFLOW_FERNET_KEY: EOzDIqFyIuHHYoLnDH_EGrnWZxYZ5NglvlKfHHhXl74=
  AIRFLOW_SECRET_KEY: airflow-secret-key


  AIRFLOW_ADMIN_USERNAME: admin
  AIRFLOW_ADMIN_PASSWORD: admin
  AIRFLOW_ADMIN_EMAIL: example@mail.com
  AIRFLOW_ADMIN_FIRSTNAME: Admin
  AIRFLOW_ADMIN_LASTNAME: User

  POSTGRES_USER: backend
  POSTGRES_HOST: postgres.team-4-ns.svc.cluster.local
  POSTGRES_PASSWORD: backend
  POSTGRES_DB: backend
  INTERNAL_POSTGRES_PORT: "5432"
  POSTGRES_PORT: "5433"

  AIRFLOW_DB_USER: airflow
  AIRFLOW_DB_PASSWORD: airflow
  AIRFLOW_DB_NAME: airflow
  AIRFLOW_DB_PORT: "5432"


  CLICKHOUSE_USER: clickhouse
  CLICKHOUSE_HOST: clickhouse.team-4-ns.svc.cluster.local
  CLICKHOUSE_PASSWORD: clickhouse
  CLICKHOUSE_DB: default
  CLICKHOUSE_PORT: "8124"
  CLICKHOUSE_NATIVE_PORT: "9001"
  INTERNAL_CLICKHOUSE_PORT: "9000"


  AIRFLOW_CONN_POSTGRES_DEFAULT: postgres://backend:backend@postgres.team-4-ns.svc.cluster.local:5432/backend
  AIRFLOW_CONN_CLICKHOUSE_DEFAULT: clickhouse://clickhouse:clickhouse@clickhouse.team-4-ns.svc.cluster.local:9000/default

  BACKEND_PORT: "8000"
  TEST_BACKEND_LOGIN: abraham
  TEST_BACKEND_PASSWORD: "12345678"

  JWT_SECRET_KEY: change-me-to-a-long-random-secret-string-for-hs256
  JWT_ACCESS_EXPIRE_MINUTES: "30"
  JWT_REFRESH_EXPIRE_DAYS: "14"

  POSTGRES_EXPORTER_DSN: postgresql://backend:backend@postgres.team-4-ns.svc.cluster.local:5432/backend?sslmode=disable
  AIRFLOW_DB_EXPORTER_DSN: postgresql://airflow:airflow@airflow-db.team-4-ns.svc.cluster.local:5432/airflow?sslmode=disable

  GRAFANA_PORT: "3000"
  GRAFANA_ADMIN_USER: admin
  GRAFANA_ADMIN_PASSWORD: admin