apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: book-project
type: Opaque
stringData:

  # ---------------- AIRFLOW ----------------
  AIRFLOW_FERNET_KEY: EOzDIqFyIuHHYoLnDH_EGrnWZxYZ5NglvlKfHHhXl74=
  AIRFLOW_SECRET_KEY: airflow-secret-key

  AIRFLOW_ADMIN_USERNAME: admin
  AIRFLOW_ADMIN_PASSWORD: admin
  AIRFLOW_ADMIN_EMAIL: example@mail.com
  AIRFLOW_ADMIN_FIRSTNAME: Admin
  AIRFLOW_ADMIN_LASTNAME: User

  # ---------------- POSTGRES ----------------
  POSTGRES_USER: backend
  POSTGRES_PASSWORD: backend

  # ---------------- AIRFLOW DB ----------------
  AIRFLOW_DB_USER: airflow
  AIRFLOW_DB_PASSWORD: airflow

  # ---------------- CLICKHOUSE ----------------
  CLICKHOUSE_USER: clickhouse
  CLICKHOUSE_PASSWORD: clickhouse

  # ---------------- CONNECTIONS ----------------
  AIRFLOW_CONN_POSTGRES_DEFAULT: postgresql://backend:backend@postgres:5432/backend
  AIRFLOW_CONN_CLICKHOUSE_DEFAULT: clickhouse://clickhouse:clickhouse@clickhouse:9000/default

  # ---------------- JWT ----------------
  JWT_SECRET_KEY: change-me-to-a-long-random-secret-string-for-hs256

  # ---------------- EXPORTERS ----------------
  POSTGRES_EXPORTER_DSN: postgresql://backend:backend@postgres:5432/backend?sslmode=disable
  AIRFLOW_DB_EXPORTER_DSN: postgresql://airflow:airflow@airflow-db:5432/airflow?sslmode=disable

  # ---------------- GRAFANA ----------------
  GRAFANA_ADMIN_USER: admin
  GRAFANA_ADMIN_PASSWORD: admin

  # ---------------- AIRFLOW CORE DB ----------------
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow