from os import environ
from dotenv import load_dotenv


load_dotenv()


def get_var(key: str) -> str:
    var = environ.get(key)
    assert var, f"required env variable {key} not found"
    return var


JWT_SECRET_KEY = get_var("JWT_SECRET_KEY")
JWT_ALGORITHM = "HS256"
JWT_ACCESS_EXPIRE_MINUTES = int(environ.get("JWT_ACCESS_EXPIRE_MINUTES", "15"))
JWT_REFRESH_EXPIRE_DAYS = int(environ.get("JWT_REFRESH_EXPIRE_DAYS", "14"))

POSTGRES_HOST = get_var("POSTGRES_HOST")
POSTGRES_PORT = get_var("POSTGRES_PORT")
POSTGRES_DB = get_var("POSTGRES_DB")
POSTGRES_USER = get_var("POSTGRES_USER")
POSTGRES_PASSWORD = get_var("POSTGRES_PASSWORD")
INTERNAL_POSTGRES_PORT = get_var("INTERNAL_POSTGRES_PORT")

CLICKHOUSE_HOST = get_var("CLICKHOUSE_HOST")
CLICKHOUSE_PORT = get_var("CLICKHOUSE_PORT")
CLICKHOUSE_DB = get_var("CLICKHOUSE_DB")
CLICKHOUSE_USER = get_var("CLICKHOUSE_USER")
CLICKHOUSE_PASSWORD = get_var("CLICKHOUSE_PASSWORD")
INTERNAL_CLICKHOUSE_PORT = get_var("INTERNAL_CLICKHOUSE_PORT")

TEST_BACKEND_LOGIN = get_var("TEST_BACKEND_LOGIN")
TEST_BACKEND_PASSWORD = get_var("TEST_BACKEND_PASSWORD")
